defaults: &defaults
  host: harriers.heroku.com
  port: 27017

development:
  <<: *defaults
  database: hhh_development

test:
  <<: *defaults
  database: hhh_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: hhh
  username: site
  password: HashesAndHashes
