defaults: &defaults
  host: localhost
  port: 27017

development:
  <<: *defaults
  database: hhh_development

test:
  <<: *defaults
  database: hhh_test

# set these environment variables on your prod server
production:
  host: staff.mongohq.com
  port: 10053
  database: app574782
  username: site
  password: HashesAndHashes
